# Gauss-Jordan elimination

Adapted from https://github.com/AugustoCL/gauss_jordan_elimination

More information about Gauss-Jordan elimination can be found at https://people.math.harvard.edu/~knill/teaching/math19b_2011/handouts/lecture05.pdf

In [1]:
using LinearAlgebra

In [2]:
# Swap two lines of a matrix
function swap_rows(A::Matrix, i::T, nlinha::T) where {T<:Integer}
    for n ∈ (i+1):nlinha        # iterate over lines above to check if could be swap
        if A[n,i] ≠ 0.0         # condition to swap row
            L = copy(A[i,:])    # copy line to swap
            A[i,:] = A[n,:]     # swap occur
            A[n,:] = L
            return true
        end
    end

    return false
end

swap_rows (generic function with 1 method)

In [3]:
# Solve a linear system using Gauss-Jordan elimination
# The system can be underdetermined, but not overdetermined
function gauss_jordan(A::Matrix{T}, override::Bool = true) where {T<:Number}
    
    B = override ? A : copy(A)
    
    # convert to float to avoid InexactError: Int64()
    (T <: Integer) && (B = convert.(Float64, B))

    # check if matrix is singular
    m, n = size(B)
    @assert m < n "The number of rows must be less than the number of columns"

    # we record the basis index vector
    basis = zeros(Int64, m)

    k = 1
    i = 1
    
    while (k < m+1) && (i < n)
        pivot = true

        # can we find a pivot element in the current row?
        if B[k,i] == 0.0
            if !swap_rows(B, k, m)
                pivot = false
            end
        end

        if pivot
            basis[k] = i

            @. B[k,:] = B[k,:] / B[k,i]

            for j ∈ axes(B, 1)                          # iterate each line for each pivot column, except pivot line
                if j ≠ k                                # jump pivot line
                    @. B[j,:] = B[j,:] - B[k,:]*B[j,i]  # apply Gauss-Jordan elimination
                end
            end
            k += 1
        end
 
        i += 1
    end

    @assert basis[m] ≠ 0 "Matrix is not of full row rank."
    
    return B, basis
end

gauss_jordan (generic function with 2 methods)

## Examples

In [9]:
A = Float64[0 4 8 1  1 4
            4 5 6 8  1 11
            1 3 0 4  1 8
            4 5 67 23 1 0];
(m,n) = size(A)
B, basis = gauss_jordan(A, false);

In [10]:
basis

4-element Vector{Int64}:
 1
 2
 3
 4

In [11]:
A[:,basis]*B[:,n]-A[:,n]

4-element Vector{Float64}:
  0.0
  0.0
  1.7763568394002505e-15
 -3.552713678800501e-15

In [12]:
B

4×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  -0.278899   -0.479633
 0.0  1.0  0.0  0.0   0.277064    1.58569
 0.0  0.0  1.0  0.0  -0.0275229  -0.409174
 0.0  0.0  0.0  1.0   0.111927    0.930642

In [16]:
A = Float64[0 4 8 0 1  1 4
            4 5 6 0 8  1 11
            1 3 0 0 4  1 8
            4 5 67 0 23 1 0];
B, basis = gauss_jordan(A, false);

In [17]:
A[:,basis]*B[:,n]-A[:,n]

4-element Vector{Float64}:
 -2.220446049250313e-16
  0.0
  0.0
 -4.440892098500626e-16

In [18]:
basis

4-element Vector{Int64}:
 1
 2
 3
 5

In [15]:
A = [ 1 2 
    3 4
    5 6 ]
B, basis = gauss_jordan(A, false)

LoadError: AssertionError: The number of rows must be less than the number of columns

In [ ]:
A = Float64[0 4 8 0 4
            4 5 6 4 11
            1 3 0  1 8
            4 5 67 4 0];
(m,n) = size(A)
B, basis = gauss_jordan(A, false);

In [ ]:
A = Float64[0 4 8 1  1 4
            4 5 6 8  1 11
            1 3 0 4  1 8
            4 5 67 23 1 0];
(m,n) = size(A)
B, basis = gauss_jordan(A, true);

In [ ]:
A

In [ ]:
A = Float64[0 4 8 1 1
            4 5 6 8 1
            1 3 0 4 1
            4 5 67 23 1 ];
b = [ 4 ; 11 ; 8; 0]
B, basis = gauss_jordan([A b]);

In [ ]:
[A b]

In [ ]:
B