# Résolution de systèmes linéaires et inversion

Nous considérons le système linéaire
$$
Ax = b
$$
où $A \in \mathbb{R}^{n \times n}$, $b \in \mathbb{R}^n$, et nous cherchons à déterminer le vecteur $x \in \mathbb{R}^n$. Nous supposons de plus que le rang de $A$ vaut $n$.

In [4]:
using LinearAlgebra
using BenchmarkTools

## Temps de calul

Nous allons créer un matrice test qui nous servira à calculer les temps de calcul en utilisant l'inversion matricielle ou les techniques de factorisation. L'inversion prend $O(n^3)$ opérations, tandis que la factorisation requiert $O(n^2)$ opérations, où $n$ est la dimension de $A$, $b$ et $x$.

In [5]:
n = 10000

10000

In [6]:
A = zeros(n,n)
for i = 1:n
    A[i,i] = 2.0
end
for i = 1:n-1
    A[i,i+1] = A[i+1,i] = -1.0
end

In [7]:
A

10000×10000 Matrix{Float64}:
  2.0  -1.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   2.0  -1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   2.0  -1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   2.0  -1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   2.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   2.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   

In [8]:
inv(A)

10000×10000 Matrix{Float64}:
 0.9999      0.9998      0.9997      …  0.00029997  0.00019998  9.999e-5
 0.9998      1.9996      1.9994         0.00059994  0.00039996  0.00019998
 0.9997      1.9994      2.9991         0.00089991  0.00059994  0.00029997
 0.9996      1.9992      2.9988         0.00119988  0.00079992  0.00039996
 0.9995      1.999       2.9985         0.00149985  0.0009999   0.00049995
 0.9994      1.9988      2.9982      …  0.00179982  0.00119988  0.00059994
 0.9993      1.9986      2.9979         0.00209979  0.00139986  0.00069993
 0.9992      1.9984      2.9976         0.00239976  0.00159984  0.00079992
 0.9991      1.9982      2.9973         0.00269973  0.00179982  0.00089991
 0.999       1.998       2.997          0.0029997   0.0019998   0.0009999
 0.9989      1.9978      2.9967      …  0.00329967  0.00219978  0.00109989
 0.9988      1.9976      2.9964         0.00359964  0.00239976  0.00119988
 0.9987      1.9974      2.9961         0.00389961  0.00259974  0.00129987

Nous pouvons déjà remarque que $A$ est creuse, alors que son inverse est dense.

Créons le membre de droite du système.

In [9]:
b = ones(n)

10000-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

Nous résolvons à présent le système avec les deux techniques.

In [10]:
x1 = inv(A)*b

10000-element Vector{Float64}:
  5000.000000045538
  9999.000000091077
 14997.000000136684
 19994.000000182154
 24990.000000227927
 29985.00000027337
 34979.00000031873
 39972.00000036431
 44964.0000004103
 49955.00000045585
 54945.00000050121
 59934.00000054674
 64922.00000059278
     ⋮
 59934.00000044705
 54945.00000040976
 49955.00000037252
 44964.00000033524
 39972.00000029784
 34979.00000026078
 29985.000000223507
 24990.000000186257
 19994.00000014891
 14997.000000111753
  9999.000000074457
  5000.000000037227

In [11]:
x2 = A\b

10000-element Vector{Float64}:
  5000.000000045416
  9999.000000090831
 14997.000000136246
 19994.000000181662
 24990.00000022708
 29985.000000272492
 34979.0000003179
 39972.00000036331
 44964.00000040873
 49955.00000045414
 54945.00000049956
 59934.00000054497
 64922.00000059038
     ⋮
 59934.00000044709
 54945.00000040984
 49955.00000037258
 44964.00000033532
 39972.00000029806
 34979.0000002608
 29985.000000223543
 24990.000000186286
 19994.00000014903
 14997.000000111771
  9999.000000074513
  5000.000000037257

Comparons la précision des résultats.

In [12]:
[norm(A*x1-b), norm(A*x2-b)]

2-element Vector{Float64}:
 6.092394679123966e-6
 9.80680834030312e-8

Nous voyons que la technique de factorisation est légèremement plus précise.

Comparons les temps d'exécution.

In [13]:
@benchmark inv(A)*b

BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 44.874 s (0.00% GC) to evaluate,
 with a memory estimate of 767.98 MiB, over 8 allocations.

In [14]:
@benchmark A\b

BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 10.997 s (0.00% GC) to evaluate,
 with a memory estimate of 763.09 MiB, over 6 allocations.

Nous allons à présent exploiter le caractère creux de $A$.

In [15]:
using SparseArrays

In [16]:
A2 = sparse(A)

10000×10000 SparseMatrixCSC{Float64, Int64} with 29998 stored entries:
⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦

In [17]:
inv(A2)

LoadError: The inverse of a sparse matrix can often be dense and can cause the computer to run out of memory. If you are sure you have enough memory, please convert your matrix to a dense matrix, e.g. by calling `Matrix`.

Nous voyons que Julia détecte que l'opération d'inversion serait inefficace au niveau mémoire.

In [18]:
x3 = A2\b

10000-element Vector{Float64}:
  4999.999999895034
  9998.99999979007
 14996.999999685106
 19993.999999580148
 24989.999999475192
 29984.999999370233
 34978.99999926528
 39971.99999916034
 44963.99999905539
 49954.99999895044
 54944.999998845495
 59933.99999874056
 64921.999998635605
     ⋮
 59933.99999992769
 54944.999999933745
 49954.99999993978
 44963.999999945816
 39971.99999995184
 34978.99999995786
 29984.999999963875
 24989.999999969892
 19993.999999975913
 14996.999999981937
  9998.99999998796
  4999.999999993979

In [19]:
@benchmark A2\b

BenchmarkTools.Trial: 714 samples with 1 evaluation.
 Range (min … max):  4.781 ms … 101.330 ms  ┊ GC (min … max): 0.00% … 12.80%
 Time  (median):     6.395 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   6.984 ms ±   5.542 ms  ┊ GC (mean ± σ):  0.71% ±  0.84%

                  ▁▃▆█▆▂▁                                      
  ▂▁▁▂▁▂▂▂▂▂▂▂▁▃▅▄████████▆▄▄▄▄▄▃▄▂▃▃▃▃▃▃▃▃▃▂▂▃▂▂▂▂▃▃▁▂▂▁▂▂▂▂ ▃
  4.78 ms         Histogram: frequency by time        9.41 ms <

 Memory estimate: 3.97 MiB, allocs estimate: 61.

In [20]:
norm(A*x3-b)

1.812764511440225e-7

La précision reste similaire au cas dense, mais le temps d'exécution est significativement plus faible.

## Précision des résultats

Nous allons modifier la diagonale de la matrice pour accentuer les résultats.

In [ ]:
for i = 1:n
    A[i,i] = 10.0^(-i)
end

A

Nous calculons le système suivant les deux techniques.

In [ ]:
x1 = inv(A)*b

In [ ]:
x2 = A\b

Calculons aussi en utilisant une matrice creuse.

In [ ]:
A2 = sparse(A)

In [ ]:
x3 = A2\b

In [ ]:
[norm(A*x1-b) norm(A*x2-b) norm(A*x3-b)]

À nouveau, nous voyons que la technique d'inversion donne des résultats moins intéressants.

Le phénonème peut être observé même sur des matrices de petite dimension quand la matrice est presque singulière.

In [ ]:
b = [1.0 ; 1.0]
M = [ 1.01 1+10^(-12) ; 1+10^(-12) 1.01 ]

In [ ]:
det(M)

In [ ]:
x1 = inv(M)*b

In [ ]:
x2 = M\b

In [ ]:
[ norm(M*x1-b) norm(M*x2-b) ]

L'inversion est un peu moins précise, mais acceptable. Considérons une situation encore plus proche de la singularité.

In [ ]:
M = [ 1.0 1+10^(-8) ; 1+10^(-8) 1.0 ]

In [ ]:
det(M)

In [ ]:
x1 = inv(M)*b

In [ ]:
x2 = M\b

In [ ]:
[ norm(M*x1-b) norm(M*x2-b) ]

Ici, la précision est nettement meilleure avec la factorisation.

Remarquons en fait qu'inverser une matrice revient à résoudre un système linéaire pour chaque vecteur de la base canonique.

In [ ]:
Minv = M\I

In [ ]:
x3 = Minv*b

In [ ]:
norm(M*x3-b)

On retrouve la même précision qu'avec l'utilisation de la fonction `inv`. En fait, les matrices sont les mêmes!

In [ ]:
Minv-inv(M)

Utiliser l'inversion revient donc à effectuer une étape coûteuse de calcul préalable, et à accumuler davantage les erreurs de calcul.