# Factorisation LU et simplexe

In [1]:
using LinearAlgebra

## Considérons la matrice

In [2]:
A = [ 1.0 3 4 5 2.0 1 ; 2 2 2 2 2 0 ; 1 3 2 4 1 1; 0 0 1 3 0 0; 2 2 1 3 3 1 ]

5×6 Matrix{Float64}:
 1.0  3.0  4.0  5.0  2.0  1.0
 2.0  2.0  2.0  2.0  2.0  0.0
 1.0  3.0  2.0  4.0  1.0  1.0
 0.0  0.0  1.0  3.0  0.0  0.0
 2.0  2.0  1.0  3.0  3.0  1.0

In [3]:
(m,n) = size(A)

(5, 6)

In [4]:
B = A[:,1:5]

5×5 Matrix{Float64}:
 1.0  3.0  4.0  5.0  2.0
 2.0  2.0  2.0  2.0  2.0
 1.0  3.0  2.0  4.0  1.0
 0.0  0.0  1.0  3.0  0.0
 2.0  2.0  1.0  3.0  3.0

$B$ est bien une base puisque la matrice est de rang plein.

In [5]:
rank(B)

5

Nous pouvons caluler la matrice $A$ par rapport à cette base, comme dans le tableau du simplexe.

In [6]:
B\A

5×6 Matrix{Float64}:
  1.0   0.0  0.0   0.0   0.0  -0.833333
  0.0   1.0  0.0   0.0   0.0   0.5
 -0.0  -0.0  1.0  -0.0  -0.0  -0.333333
  0.0   0.0  0.0   1.0   0.0   0.111111
  0.0   0.0  0.0   0.0   1.0   0.555556

La fonction `lu` permet d'obtenir la décomposition $LU$.

In [7]:
F1 = lu(B)

LU{Float64, Matrix{Float64}}
L factor:
5×5 Matrix{Float64}:
 1.0  0.0   0.0  0.0  0.0
 0.5  1.0   0.0  0.0  0.0
 0.5  1.0   1.0  0.0  0.0
 0.0  0.0  -0.5  1.0  0.0
 1.0  0.0   0.5  0.6  1.0
U factor:
5×5 Matrix{Float64}:
 2.0  2.0   2.0   2.0   2.0
 0.0  2.0   3.0   4.0   1.0
 0.0  0.0  -2.0  -1.0  -1.0
 0.0  0.0   0.0   2.5  -0.5
 0.0  0.0   0.0   0.0   1.8

Vérifions que nous pouvons retrouver $B$.

In [8]:
F1.L*F1.U - B

5×5 Matrix{Float64}:
  1.0  -1.0  -2.0  -3.0  0.0
 -1.0   1.0   2.0   3.0  0.0
  0.0   0.0   0.0   0.0  0.0
  0.0   0.0   0.0   0.0  0.0
  0.0   0.0   0.0   0.0  0.0

Le produit ne donne pas $B$! C'est qu'en pratique, la factorisation implique des opérations de pivotages à des fins de stabilité numérique. Le pivotage est stocké dans `F.p`.

In [9]:
F1.L*F1.U-B[F1.p,1:5]

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Afin d'éviter les complications techniques, nous allons désactiver le pivotage. Notons toutefois que ceci est fortement déconseillé du point de vue de la stabilité numérique.

In [10]:
F1 = lu(B, Val(false); check = true)

LU{Float64, Matrix{Float64}}
L factor:
5×5 Matrix{Float64}:
 1.0   0.0   0.0  0.0  0.0
 2.0   1.0   0.0  0.0  0.0
 1.0  -0.0   1.0  0.0  0.0
 0.0  -0.0  -0.5  1.0  0.0
 2.0   1.0   0.5  0.6  1.0
U factor:
5×5 Matrix{Float64}:
 1.0   3.0   4.0   5.0   2.0
 0.0  -4.0  -6.0  -8.0  -2.0
 0.0   0.0  -2.0  -1.0  -1.0
 0.0   0.0   0.0   2.5  -0.5
 0.0   0.0   0.0   0.0   1.8

In [11]:
F1.L*F1.U-B

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Supposons que nous échangons la $3^e$ et la $6^e$ colonnes. La nouvelle base est

In [12]:
B = A[:, [1, 2, 4, 5, 6 ]]

5×5 Matrix{Float64}:
 1.0  3.0  5.0  2.0  1.0
 2.0  2.0  2.0  2.0  0.0
 1.0  3.0  4.0  1.0  1.0
 0.0  0.0  3.0  0.0  0.0
 2.0  2.0  3.0  3.0  1.0

In [13]:
rank(B)

5

In [14]:
F2 = lu(B, Val(false); check = true)

LU{Float64, Matrix{Float64}}
L factor:
5×5 Matrix{Float64}:
 1.0   0.0   0.0   0.0  0.0
 2.0   1.0   0.0   0.0  0.0
 1.0  -0.0   1.0   0.0  0.0
 0.0  -0.0  -3.0   1.0  0.0
 2.0   1.0  -1.0  -0.0  1.0
U factor:
5×5 Matrix{Float64}:
 1.0   3.0   5.0   2.0   1.0
 0.0  -4.0  -8.0  -2.0  -2.0
 0.0   0.0  -1.0  -1.0   0.0
 0.0   0.0   0.0  -3.0   0.0
 0.0   0.0   0.0   0.0   1.0

Comparons les facteurs de la première et de la seconde base.

In [15]:
F1.L - F2.L

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  2.5  0.0  0.0
 0.0  0.0  1.5  0.6  0.0

In [16]:
F1.U - F2.U

5×5 Matrix{Float64}:
 0.0  0.0  -1.0   3.0   1.0
 0.0  0.0   2.0  -6.0   0.0
 0.0  0.0  -1.0   0.0  -1.0
 0.0  0.0   0.0   5.5  -0.5
 0.0  0.0   0.0   0.0   0.8

Nous pouvons remarquer que les trois premières lignes de la matrice triangulaire inférieure sont identitiques, mais pas les deux suivantes. De la même manière, les deux premières colonnes de la matrice triangulaire supérieure coïncident.

## Mise à jour des facteurs

Essayons de former F2.U à partir de F1.U

In [17]:
L = F1.L
U = F1.U

5×5 Matrix{Float64}:
 1.0   3.0   4.0   5.0   2.0
 0.0  -4.0  -6.0  -8.0  -2.0
 0.0   0.0  -2.0  -1.0  -1.0
 0.0   0.0   0.0   2.5  -0.5
 0.0   0.0   0.0   0.0   1.8

Ajoutons $L^{-1}a_6$ (que nous obtenons normalement lors du pivotage lors du changement de base). et retirons la $3^e$ colonne du U.

In [18]:
U[:,3:4] = U[:,4:5] 
U[:,m] = F1.L\A[:,6]
U

5×5 Matrix{Float64}:
 1.0   3.0   5.0   2.0   1.0
 0.0  -4.0  -8.0  -2.0  -2.0
 0.0   0.0  -1.0  -1.0   0.0
 0.0   0.0   2.5  -0.5   0.0
 0.0   0.0   0.0   1.8   1.0

Nous avons bien que le produit des deux facteurs donnent à présent la base recherchée.

In [19]:
B-L*U

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Nous devons annuler l'élément (4,3). En se rappelant que le produit $m^TB$ revient à construire une combinaison linéaire des lignes de $B$, nous construisons

In [20]:
m1 = [ 0 0 2.5 1 0 ]

1×5 Matrix{Float64}:
 0.0  0.0  2.5  1.0  0.0

In [21]:
M = zeros(m,m)+I
M[4,:] = m1
M

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  2.5  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [22]:
M*U

5×5 Matrix{Float64}:
 1.0   3.0   5.0   2.0   1.0
 0.0  -4.0  -8.0  -2.0  -2.0
 0.0   0.0  -1.0  -1.0   0.0
 0.0   0.0   0.0  -3.0   0.0
 0.0   0.0   0.0   1.8   1.0

In [23]:
Minv = inv(M)

5×5 Matrix{Float64}:
 1.0  0.0   0.0  0.0  0.0
 0.0  1.0   0.0  0.0  0.0
 0.0  0.0   1.0  0.0  0.0
 0.0  0.0  -2.5  1.0  0.0
 0.0  0.0   0.0  0.0  1.0

Nous n'avons pas besoin de stocker tout $M$. Il suffit de stocker le vecteur donnant la combinaison des deux lignes.

In [24]:
p = 3
m1 = [-U[p+1,p]/U[p,p] 1]

1×2 Matrix{Float64}:
 2.5  1.0

In [25]:
U[p+1,p:m] = m1*U[p:p+1,p:m]

1×3 Matrix{Float64}:
 0.0  -3.0  0.0

Nous mettons à jour le facteur $L$ en appliquant l'inverse du facteur $M$.

In [26]:
L[p:m,p] = L[p:m,p:p+1]*[ 1 ; -m1[1]]

3-element Vector{Float64}:
  1.0
 -3.0
 -1.0000000000000002

Le produit des nouveaux facteurs $L$ et $U$ donnent toujours $B$.

In [27]:
L*U - B

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

En suivant le même raisonnement, nous construisons par la suite

In [28]:
p = 4
m1 = [-U[p+1,p]/U[p,p] 1]
U[p+1,p:m] = m1*U[p:p+1,p:m]
U

5×5 Matrix{Float64}:
 1.0   3.0   5.0   2.0           1.0
 0.0  -4.0  -8.0  -2.0          -2.0
 0.0   0.0  -1.0  -1.0           0.0
 0.0   0.0   0.0  -3.0           0.0
 0.0   0.0   0.0   2.22045e-16   1.0

Nous retrouvons bien (aux erreurs numériques près) le facteur $U$ associé à la factorisation de la seconde base.

In [29]:
F2.U-U

5×5 Matrix{Float64}:
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0  -2.22045e-16  0.0

Nous mettons à nouveau à jour le facteur L.

In [30]:
L[p:m,p] = L[p:m,p:p+1]*[ 1 ; -m1[1]]

2-element Vector{Float64}:
 1.0
 1.1102230246251565e-16

Les deux facteurs ont bien la forme désirée.

In [31]:
[L U]

5×10 Matrix{Float64}:
 1.0   0.0   0.0  0.0          0.0  1.0   3.0   5.0   2.0           1.0
 2.0   1.0   0.0  0.0          0.0  0.0  -4.0  -8.0  -2.0          -2.0
 1.0  -0.0   1.0  0.0          0.0  0.0   0.0  -1.0  -1.0           0.0
 0.0  -0.0  -3.0  1.0          0.0  0.0   0.0   0.0  -3.0           0.0
 2.0   1.0  -1.0  1.11022e-16  1.0  0.0   0.0   0.0   2.22045e-16   1.0

Leur produit donne également la base recherchée.

In [32]:
B - L*U

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

En pratique, la méthode devra être affinée pour tenir compte des pivots liés à la factorisation LU.